language: node_js
node_js:
  - 0.10

# switch to chrome, http://stackoverflow.com/questions/19255976/how-to-make-travis-execute-angular-tests-on-chrome-please-set-env-variable-chr
env: BROWSERS=firefox E2E_BROWSERS=Firefox

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run update-webdriver

script:
  - scripts/private/test-all.sh
