language: node_js
node_js:
  - 0.10

# switch to chrome, http://stackoverflow.com/questions/19255976/how-to-make-travis-execute-angular-tests-on-chrome-please-set-env-variable-chr
# chrome loading via karma, https://github.com/karma-runner/karma/issues/1144#issuecomment-53633076
# chrome setting, https://github.com/MrOrz/SeeSS/blob/master/.travis.yml
# npm setting, https://www.npmjs.com/package/grunt-angular-toolbox
# env: BROWSERS=firefox E2E_BROWSERS=Firefox
env: BROWSERS=chrome E2E_BROWSERS=chrome

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run update-webdriver

script:
  - scripts/private/test-all.sh
